[project]
name = "streamlit-sqlitecloud-starter"
version = "0.1.0"
description = "Starter template: Streamlit + SQLAlchemy + SQLiteCloud"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqladmin[auth]",
    "sqlalchemy>=2.0",
    "sqlalchemy-sqlitecloud>=0.1",
    "streamlit>=1.65.0",
]

[tool.uv.sources]
sqladmin = { git = "https://github.com/smithyhq/sqladmin.git" }
